mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8085
spring:
  datasource:
    username: root
    password: admin123
    url: jdbc:mysql://localhost:3306/loginDemo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
